[package]
name = "tarkov-map"
version = "0.1.0"
edition = "2024"
default-run = "main"

[dependencies]
base64 = "0.22.1"
color-eyre = "0.6.5"
eframe = "0.33.3"
egui_extras = { version = "0.33.3", features = ["svg"] }
env_logger = { version = "0.11.8", features = ["auto-color", "humantime"] }
reqwest = { version = "0.13.1", features = ["json"] }
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.149"
tokio = { version = "1.49.0", features = ["full"] }
